language: generic

# conditional build
conditions: v1

# build only the following:
#   master branch
#   btw branch
#   branches starting with `ci-` or `ci/`
#   commits with `[build pdf]` in the commit message
if: branch == master || branch =~ ^(?i:ci)(-|\/).* || commit_message =~ /^.*\[build pdf\].*$/

# install texlive for using pdflatex and biber in the build
install:
- source ./bin/install_texlive.sh

# cache the texlive installation and all installed packages
cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"

# run the PDF build-steps (pdflatex and biber) for
# main file: paper.tex
# output filename: Self-Healing.pdf
script:
- "./bin/build.sh paper Self-Healing.pdf"

# use deployment to push back the resulting PDF into the corresponding branch
deploy:
  skip_cleanup: true
  provider: script
  script: "./bin/travis-push.sh Self-Healing.pdf"
  on:
    all_branches: true

# secure GH_TOKEN for Github API authentication
env:
  global:
    secure: NIiq3ckrcPaqinAddmNSrbdzC5mFlUC9B8yggRfgOkWZ9zHVVouFViEYASeUbP9Idb+TE1Yf3JgsHD/rJo0nsxoEKnUQ+K5nL9TW5L20yh4W+Enxqw1MfGUMtmJbUYXfqZOYEDZPw5842M2uIY5QvnzuxnHKC41PupgknarIEml6y/nqsuCDYv13+vojVRyp+5AI1PKbtwc2gJv5lBR88LGjzt7WFnzW4v/8u7i18S7hxuN1sDTmjbaY3BIOU0Dq7r1lGHi6e0xNEp2pLFj8FJeYM6YkLf+1eM+vSNMety8zLJsp1wRvS5JifjeGANr+iemhSKGSsk8f49JmJltgE8ylrZLQybzPtQs2HgjBKfl/9ctW0TnJY052NBD8AAiq07Dywvvuxea6lLNhKkbWX7GRb+xmiogkYodjQeUqd4GpKiKdg21IlLg3/7d+UrvpfA/7/QAq0Yy5fd0NvvKtSNC3EdB9DUiWatK8r2ER8UhPJgnD9GAk02qTkZyj+PCvq6tZMnd8mhy/SuLoGSGdWdUwMo7V4FlvN4Q5UxL+xpAeX+vIbAOZH0xJVgkvd+CafKMs2QtQulsJzzJHFITVccv2FQIoxjfy4F7zPp1qNSr4wdiZBCP/8sCybcNLmsp052ZqhFUZF3PkSlflztrFwkSn5/n/3owDNg/fNapsgG0=
